name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
env:
  GITHUB_USER: 'sandreas'
  PROJECT_NAME: 'Avalonia.SimplePreferences'
  PROJECT_PATH: 'Avalonia.SimplePreferences/Avalonia.SimplePreferences.csproj'
  PACKAGE_ID: 'Sandreas.Avalonia.SimplePreferences'
  DOTNET_VERSION: '8.0.x'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Get version
        id: version
        uses: battila7/get-version-action@v2

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ steps.version.outputs.version-without-v }}

      # - name: Test
      #  run: dotnet test --configuration Release /p:Version=${{ steps.version.outputs.version-without-v }} --no-build

      - name: Pack
        run: dotnet pack --configuration Release --include-symbols /p:PackageId=${{env.PACKAGE_ID}} /p:Version=${{ steps.version.outputs.version-without-v }} --no-build --output .

      - name: Push
        run: |
          dotnet nuget push ${{ env.PACKAGE_ID }}.${{ steps.version.outputs.version-without-v }}.nupkg --source https://nuget.pkg.github.com/${{ env.GITHUB_USER }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} && dotnet nuget push ${{ env.PROJECT_NAME }}.${{ steps.version.outputs.version-without-v }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}           
